### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by LifeIsStrange** [GPUOpen-LibrariesAndSDKs/LiquidVR#1]
In the README.md you say that liquid VR use direct 3D 11 but you mention Async Compute which is a direct 3D 12 feature.  

Thanks for opensourcing :)  you are altruists, I love you.

**Comment by jstewart-amd** [comment]
Are you referring to this line from README.md?
- **Async Compute** : Provides in Direct3D 11 a subset of functionality similar to async-compute functionality in Direct3D 12.

GCN hardware supports Async Compute, but it is not exposed in standard Direct3D 11. What the readme is saying is that, using LiquidVR, you can access this feature in Direct3D 11, something you cannot do without LiquidVR. It is not a typo.

Changing the subject, we are probably going to disable the issue system on this repo, at least temporarily, until we have people assigned to review and track the issues. But before we do that, I wanted to say thanks for the feedback.
