### ISSUE TITLE
some printer's error in LiquidVR.pdf

### ISSUE THREAD

**Issue by vicdxxx** [GPUOpen-LibrariesAndSDKs/LiquidVR#5]
So glad to use your LiquidVR as a SDK, nice GPU affinity. And I want to record  printer's errors I found in
LiquidVR.pdf here, improve this doc for more reader.
1.QueueSemaphoreSignal
Queue a sempahore signal ...

**Comment by GennadiyAMD** [comment]
Hi vicdxxx,

Thanks, it's great you found LiquidVR useful.
Regarding your comment, could you please refer me to the page number where you see the typo. But if you're talking about the captions, these are method names, so QueueSemaphoreSignal and similar names are intentional.

Thanks,
Gennadiy

**Comment by vicdxxx** [comment]
@Gennadiy,

So sorry reply you until now, because I am not review this part daily(so bad, lol). I wanted to point the 'sempahore ' spell worng in the explainations of QueueSemaphoreSignal function.  I see your docs today, which has corrected.  I intend follow your new techs in liquidVR if born. New products usually ship this  season.

Vicdxxx
